# Generated by Django 6.0.1 on 2026-02-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_notification'),
        ('products', '0004_add_password_reset_otp'),
    ]

    operations = [
    ]
